webtalk_init -webtalk_dir /home/francesca/xil_proj/trig_testbench_F/project_1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 1 19:01:39 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "vrmuecv5ea3ai8io6baplilmcd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1496324083000" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.2" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key Device -value "7z030" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1496324083000"
webtalk_add_data -client sdk -key uid -value "1496324111000" -context "sdk\\\\bsp/1496324111000"
webtalk_add_data -client sdk -key hwid -value "1496324083000" -context "sdk\\\\bsp/1496324111000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1496324111000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1496324111000"
webtalk_add_data -client sdk -key uid -value "1496324113000" -context "sdk\\\\application/1496324113000"
webtalk_add_data -client sdk -key hwid -value "1496324083000" -context "sdk\\\\application/1496324113000"
webtalk_add_data -client sdk -key bspid -value "1496324111000" -context "sdk\\\\application/1496324113000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1496324113000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1496324113000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1496324113000"
webtalk_transmit -clientid 336351807 -regid "" -xml /home/francesca/xil_proj/trig_testbench_F/project_1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/francesca/xil_proj/trig_testbench_F/project_1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/francesca/xil_proj/trig_testbench_F/project_1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
